# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://ryanlennon.github.io/
baseurl: /
title: Ryan Lennon
author: Ryan Lennon
description: Personal blog
avatar: profile.jpg
email: ryanlennon07@gmail.com
github: ryanlennon # username
twitter: RyanL3nn0n
linkedin: ryanlennon07
stackoverflow: #username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: ryanlennon07
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
